version: '2'

services:
  postgres:
    image: octoon/centos7-postgres
    container_name: postgres
    hostname: postgres
    volumes:
    - /home/data/postgres:/var/lib/pgsql/9.5/data
    extra_hosts:
    - "elastic:172.16.238.72"
    - "wildfly:172.16.238.73"
    ports:
    - "5432:5432"
    networks:
      octoon:
        ipv4_address: 172.16.238.71
  elastic:
    container_name: elastic
    image: octoon/elasticsearch-centos
    hostname: elastic
    volumes:
    - /home/data/elasticsearch:/var/lib/elasticsearch
    extra_hosts:
    - "postgres:172.16.238.71"
    - "wildfly:172.16.238.73"
    ports:
    - "9200:9200"
    networks:
      octoon:
        ipv4_address: 172.16.238.72
  wildfly:
    container_name: wildfly
    image: octoon/keycloak-centos
    hostname: wildfly
    extra_hosts:
    - "postgres:172.16.238.71"
    - "elastic:172.16.238.72"
    ports:
    - "22:22"
    - "8080:8080"
    - "8443:8443"
    - "9990:9990"
    networks:
      octoon:
        ipv4_address: 172.16.238.73

networks:
  octoon:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
